version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: malang_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --requirepass '${REDIS_PASSWORD}' --appendonly yes
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli",  "${REDIS_PASSWORD}","ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  redis_data:

networks:
  app-network:
    external: true