version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: malang_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --requirepass '${REDIS_PASSWORD}' --appendonly yes
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    restart: always
    networks:
      - app-network
    depends_on:
      - backend-app1
      - backend-app2
      - frontend-app
      - portainer
      - jenkins

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge