version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: malang_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --requirepass '${REDIS_PASSWORD}' --appendonly yes
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    external: true