# 기본 애플리케이션 설정
spring:
  application:
    name: backend
  # 데이터 소스 설정 (MySQL)
  datasource:
    url: jdbc:mysql://localhost:3306/malang?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${mysql-username} # 환경 변수 등에서 주입
    password: ${mysql-password} # 환경 변수 등에서 주입
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 생성/업데이트 전략
    show-sql: true       # 실행되는 SQL 쿼리 로그 출력 여부 (디버깅 시 유용)
    properties:
      hibernate:
        format_sql: true # SQL 로그 가독성 좋게 포맷팅
    database-platform: org.hibernate.dialect.MySQLDialect # 사용할 데이터베이스 방언
  # Spring Security 기본 사용자 설정 (In-memory user)
  security:
    user:
      name: ${springSecurity-username} # 환경 변수 등에서 주입
      password: ${springSecurity-password} # 환경 변수 등에서 주입 (주의: 실제 운영 환경에서는 사용 비권장)

  # Redis 설정
  data:
    redis:
      host: ${redis_host}       # 환경 변수 등에서 주입
      port: ${redis_port}       # 환경 변수 등에서 주입
      password: ${redis_password:} # 환경 변수 등에서 주입 (값이 없으면 빈 문자열 사용)

# 서버 설정
server:
  port: 8080               # 서버 포트
  servlet:
    context-path: /api     # 애플리케이션 컨텍스트 경로

# JWT (JSON Web Token) 설정
jwt:
  secret: ${jwt-secret-token} # 환경 변수 등에서 주입 (JWT 서명 비밀키)
  access-token-validity-in-seconds: 18000 # Access Token 유효 시간 (초) - 5시간
  refresh-token-validity-in-seconds: 1209600 # Refresh Token 유효 시간 (초) - 14일

# 로깅 레벨 설정
logging:
  level:
    org:
      springframework:
        security: DEBUG # Spring Security 관련 로그 상세 출력
      example:
        backend: DEBUG  # 프로젝트 패키지 로그 상세 출력

# 외부 서비스 URL 설정
llm:
  base-url: ${localLLM} # 환경 변수 등에서 주입
speech:
  base-url: ${speechAi} # 환경 변수 등에서 주입

# OpenVidu 설정
openvidu:
  url: https://j12d110.p.ssafy.io:8443
  secret: juheonsong

# S3
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
